services:
  - type: web
    name: health-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
